### ISSUE TITLE
About switching to MIT or more developer friendly LICENSE

### ISSUE THREAD

**Issue by trivikr** [fastify/light-my-request#14]
Hi,

Thanks for building fastify - fast and low overhead framework for Node.js!
As it's approaching release 1.x.x, we're evaluating it to use in our next project.

While doing license reviews of fastify dependencies, we realized that light-my-request uses BSD-3-Clause. It was changed to MIT License in [this commit](https://github.com/fastify/light-my-request/commit/09c40c8d19f7e777096db28b8f7a3ebf79c51d8a), but it was reverted back to the [previous one](https://github.com/fastify/light-my-request/commit/a4c7f80e13c49d20f730a5da06f01897cb1a7401)

Is there a reason for not using MIT or more developer friendly License for light-my-request?
I really want to use fastify 1.x.x in production and do some performance analysis while comparing with expressjs, but this license is blocking me from doing that.

CC: @delvedor 

Regards,
Trivikram

**Comment by mcollina** [comment]
This project is a fork of http://npm.im/shot, which is licensed under BSD. Unfortunately, we cannot change this fact and we cannot relicense what they have done.

Why do you think BSD is not developer friendly? In my understanding there is marginal difference between the two.

**Comment by trivikr** [comment]
Thanks @mcollina for the response.
I went through [shot](https://github.com/hapijs/shot) and other [hapijs](https://github.com/hapijs) projects and realized that most of them are distributed under BSD-3-Clause license.

There are [minor differences](https://opensource.stackexchange.com/a/582) between BSD and MIT license. Websites like [choosealicense.com](https://choosealicense.com/) have actually explicitly [removed BSD and ISC licenses](https://github.com/github/choosealicense.com/issues/413) as MIT is much similar but simpler.

Since MIT License explicitly allows merging, publishing, sublicensing and selling it's easier to use it. The projects with BSD licenses require additional review in my organization which takes time before we can play with them.

Do you think creating an issue with [shot](https://github.com/hapijs/shot) to check whether they can switch to MIT will help?

**Comment by mcollina** [comment]
We are no lawyers, so I would recommend to talk to your lawyer and check if you can use this software. I guess you can, because MIT, BSD, Apache 2.0, ISC and many others are all considered business friendly (as an example, the Redis database is BSD).
Side note: fastify has many dependencies that are ISC - so you would have similar issues there as well. You can use http://npm.im/license-checker to verify.

> Do you think creating an issue with shot to check whether they can switch to MIT will help?

If you look at the license in his file, you can see that it goes back quite some time, and the library was originally done in Walmart. I understand it will be _very hard_ to change the license of this software at this point, and they won't have any incentives in doing that.

---

The website you cite literally says:

> However, all these freedoms are implied by the BSD license, because all these activities can be considered "use" and/or "redistribution" of the software.

This article is fairly well written: https://snyk.io/blog/mit-apache-bsd-fairest-of-them-all/.

> Websites like choosealicense.com have actually explicitly removed BSD and ISC licenses as MIT is much similar but simpler.

As noted _several times_ in the links you provided (https://github.com/github/choosealicense.com/pull/386#issuecomment-207826717, https://github.com/github/choosealicense.com/issues/413#issuecomment-219257044), the only reason BSD was removed is because of cognitive overhead and popularity. This license is actually fine.

**Comment by trivikr** [comment]
Thanks @mcollina for the explanation.

About fastify dependencies, [fastq](https://github.com/mcollina/fastq) does use ISC license and it's approval was straightforward as the projects with MIT license.

About:
> However, all these freedoms are implied by the BSD license, because all these activities can be considered "use" and/or "redistribution" of the software.

May be the lawyers don't want to take a risk with BSD, and setting up additional review to be safe.

Anyway, looks like it'll be hard to change the license to MIT. I'll go through the review process as required by my organization.

**Comment by mcollina** [comment]
From what I can tell, Hapi has been used in the most strict organizations with no problems.

Let us know if there are issues in the process.

**Comment by mcollina** [comment]
@trivikr pino is MIT but it depends on split2 which is ISC as well.

**Comment by trivikr** [comment]
Hi @mcollina, I'd a question about attribution under BSD-3-Clause license.
If I'm using fastify NodeJS server for serving requests, do I need to include attribution in the file header when sending response to customers?

**Comment by mcollina** [comment]
no you don’t.
