### ISSUE TITLE
Extend request object with custom properties

### ISSUE THREAD

**Issue by jagu-sayan** [fastify/light-my-request#227]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Add an easy way to extend Request object.

### Motivation

Allow to mock features.
For example, [@fastify/passport](https://github.com/fastify/fastify-passport) add a `user` property to `FastifyRequest` when a user is connected. I want to test my private endpoint without call an endpoint to connect the user by directly add the corresponding `user` property into request object.

### Example

Add the ability to write something like this:

```typescript
const res = await app.inject({
  method: "GET",
  url: "/api/my-private-endpoint",
  extend : {
    // Add user property to request object
    user : {
      id: "user_id",
      ...
    },
   ...
});
```

```typescript
// My endpoint handler
export default async function myPrivateEndpoint(
  req: FastifyRequest,
  res: FastifyReply
) {
  const { id } = req.params;
  const loggedUser: PassportUser = req.user;  // Use user property here
}
```

**Comment by Eomm** [comment]
This package simulates a real http request to the server, it is not designed to inject decorators to the server's `request`/`reply` objects. I think it is nor doable because the `request`/`reply` objects may have a different shape on each fastify context.

> For example, [@fastify/passport](https://github.com/fastify/fastify-passport) add a user property to FastifyRequest when a user is connected. I want to test my private endpoint without call an endpoint to connect the user by directly add the corresponding user property into request object.

In this case, you should inject a valid HTTP header that calls a mocked endpoint that returns the user you want. You will get the same result but following another path.
